{% set python_min = "3.8" %}
{% set name = "mocket" %}
{% set version = "3.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mocket-{{ version }}.tar.gz
  sha256: d080dbf888f40505a57abaa7d67df51d81cf21eff8ae09b402ce8cd997bcc320

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.22.2
    - pip
  run:
    - python >={{ python_min }}
    - puremagic
    - decorator >=4.0.0
    - urllib3 >=1.25.3
    - h11

test:
  imports:
    - mocket
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mindflayer/python-mocket
  summary: Socket Mock Framework - for all kinds of socket animals, web-clients included - with gevent/asyncio/SSL support
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
