schema_version: 1

context:
  version: "3.14.5"

package:
  name: mocket
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/mocket/mocket-${{ version }}.tar.gz
  sha256: 536f16e1c9c28894594db2a2af96c0ade99ecdbe6c7676c2d0b97c5e4d803edd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.22.2
    - pip
  run:
    - python >=${{ python_min }}
    - puremagic
    - decorator >=4.0.0
    - urllib3 >=1.25.3
    - h11
    - typing_extensions

tests:
  - python:
      imports:
        - mocket
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Socket Mock Framework - for all kinds of socket animals, web-clients included - with gevent/asyncio/SSL support
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/mocket

extra:
  recipe-maintainers:
    - ocefpaf
